// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pgs.pcare.domain;

import com.pgs.pcare.domain.Buddy;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Buddy_Roo_Configurable {
    
    declare @type: Buddy: @Configurable;
    
}
