// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pgs.pcare.domain;

import com.pgs.pcare.domain.Buddy;
import com.pgs.pcare.domain.BuddyDataOnDemand;
import com.pgs.pcare.domain.BuddyIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BuddyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BuddyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BuddyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BuddyIntegrationTest: @Transactional;
    
    @Autowired
    BuddyDataOnDemand BuddyIntegrationTest.dod;
    
    @Test
    public void BuddyIntegrationTest.testCountBuddys() {
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", dod.getRandomBuddy());
        long count = Buddy.countBuddys();
        Assert.assertTrue("Counter for 'Buddy' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BuddyIntegrationTest.testFindBuddy() {
        Buddy obj = dod.getRandomBuddy();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to provide an identifier", id);
        obj = Buddy.findBuddy(id);
        Assert.assertNotNull("Find method for 'Buddy' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Buddy' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BuddyIntegrationTest.testFindAllBuddys() {
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", dod.getRandomBuddy());
        long count = Buddy.countBuddys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Buddy', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Buddy> result = Buddy.findAllBuddys();
        Assert.assertNotNull("Find all method for 'Buddy' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Buddy' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BuddyIntegrationTest.testFindBuddyEntries() {
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", dod.getRandomBuddy());
        long count = Buddy.countBuddys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Buddy> result = Buddy.findBuddyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Buddy' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Buddy' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BuddyIntegrationTest.testFlush() {
        Buddy obj = dod.getRandomBuddy();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to provide an identifier", id);
        obj = Buddy.findBuddy(id);
        Assert.assertNotNull("Find method for 'Buddy' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBuddy(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Buddy' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BuddyIntegrationTest.testMergeUpdate() {
        Buddy obj = dod.getRandomBuddy();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to provide an identifier", id);
        obj = Buddy.findBuddy(id);
        boolean modified =  dod.modifyBuddy(obj);
        Integer currentVersion = obj.getVersion();
        Buddy merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Buddy' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BuddyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", dod.getRandomBuddy());
        Buddy obj = dod.getNewTransientBuddy(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Buddy' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Buddy' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Buddy' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BuddyIntegrationTest.testRemove() {
        Buddy obj = dod.getRandomBuddy();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Buddy' failed to provide an identifier", id);
        obj = Buddy.findBuddy(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Buddy' with identifier '" + id + "'", Buddy.findBuddy(id));
    }
    
}
