// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pgs.pcare.domain;

import com.pgs.pcare.domain.Buddy;
import com.pgs.pcare.domain.BuddyDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BuddyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BuddyDataOnDemand: @Component;
    
    private Random BuddyDataOnDemand.rnd = new SecureRandom();
    
    private List<Buddy> BuddyDataOnDemand.data;
    
    public Buddy BuddyDataOnDemand.getNewTransientBuddy(int index) {
        Buddy obj = new Buddy();
        setBuddyID(obj, index);
        setDateOfBirth(obj, index);
        setEmailId(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setPhoneNumber(obj, index);
        return obj;
    }
    
    public void BuddyDataOnDemand.setBuddyID(Buddy obj, int index) {
        Integer buddyID = new Integer(index);
        obj.setBuddyID(buddyID);
    }
    
    public void BuddyDataOnDemand.setDateOfBirth(Buddy obj, int index) {
        Date dateOfBirth = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateOfBirth(dateOfBirth);
    }
    
    public void BuddyDataOnDemand.setEmailId(Buddy obj, int index) {
        String emailId = "foo" + index + "@bar.com";
        obj.setEmailId(emailId);
    }
    
    public void BuddyDataOnDemand.setFirstName(Buddy obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void BuddyDataOnDemand.setLastName(Buddy obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void BuddyDataOnDemand.setPhoneNumber(Buddy obj, int index) {
        String phoneNumber = "phoneNumber_" + index;
        obj.setPhoneNumber(phoneNumber);
    }
    
    public Buddy BuddyDataOnDemand.getSpecificBuddy(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Buddy obj = data.get(index);
        Long id = obj.getId();
        return Buddy.findBuddy(id);
    }
    
    public Buddy BuddyDataOnDemand.getRandomBuddy() {
        init();
        Buddy obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Buddy.findBuddy(id);
    }
    
    public boolean BuddyDataOnDemand.modifyBuddy(Buddy obj) {
        return false;
    }
    
    public void BuddyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Buddy.findBuddyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Buddy' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Buddy>();
        for (int i = 0; i < 10; i++) {
            Buddy obj = getNewTransientBuddy(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
